### ISSUE TITLE
Replacing staged file with empty contents

### ISSUE THREAD

**Issue by svandragt** [hallettj/git-format-staged#11]
I've installed the husky and this package via npm but have trouble setting it up to work correctly.

I've added the following to package.json:
```
"husky": {
    "hooks": {
      "pre-commit": "git-format-staged --formatter 'eslint -c myconfig --stdin >&2' 'content/*.js'"
    }
  },
``` 
When I commit a change in a js file the file's contents are blanked, and the commit succeeds. What am I doing wrong?

**Comment by hallettj** [comment]
Hi! To use git-format-staged to check for lint errors on commit without reformatting files it's important to include the `--no-write` flag which tells git-format-staged to run the formatter command without modifying the file. By default git-format-staged assumes that the `stdout` from the formatter command should be the new content of the file. Since you are redirecting the `stdout` stream to `stderr` (with `>&2`) your command does not produce any output on `stdout`, and so your file ends up empty. Eslint doesn't output formatted file content anyway - it writes lint errors to `stdout` instead. Redirecting those to `stderr` is important because if there are errors git-format-staged only shows you the `stderr` output from the formatter command. I'll look into making a change to treat empty output from the formatter command as an error, and to print a helpful message.

Another detail is that eslint needs to know the name of the file it is checking to check it with the proper rule set. You can provide that information with the eslint option `--stdin-filename {}`. Git-format-staged will replace the `{}` with the actual file path. I know I didn't include this information in the readme; I think `--stdin-filename` might not have been available when I wrote the documentation. I'll add that info.

The full configuration I suggest you use is:

```json
"husky": {
    "hooks": {
      "pre-commit": "git-format-staged --no-write --formatter 'eslint -c myconfig --stdin --stdin-filename {} >&2' 'content/*.js'"
    }
  },
```

If your intention is not to just lint files but to automatically fix files on commit _à la_ `eslint --fix` then that's more complicated. In an ideal world you could use a command like this:

```
eslint -c myconfig --stdin --stdin-filename {} --fix-dry-run --format=hypothetical-formatter
```

The problem is that git-format-staged needs to read the updated file content from the `stdout` stream of the formatter command, but eslint does not send file content to `stdout`. In theory you could use a [custom formatter](https://eslint.org/docs/developer-guide/working-with-custom-formatters) that does the right thing. (In this context a "formatter" is a library that customizes eslint's output). Unfortunately I don't know if `hypothetical-formatter` exists. If I find a fix I'll update the documentation.
