### ISSUE TITLE
Unable to run alongside `prettier`

### ISSUE THREAD

**Issue by rogerluan** [hallettj/git-format-staged#59]
Hey 👋 

I've been trying to integrate `git-format-staged` (2.1.2) with `prettier` (2.2.1), but it's not formatting anything. I tried with husky, but I'll leave that to a 2nd moment, let's first figure out a vanilla implementation:

`.git/hooks/pre-commit` (chmod +x)

```sh
#!/bin/sh
echo "Sanity check" # This is executed just fine, which proves my precommit hook is being invoked
npx git-format-staged --formatter 'npx prettier --loglevel debug --stdin-filepath "{}"' 'src/**/*.{js,jsx,ts}'
```

Moreover, `--loglevel debug` doesn't do anything (it doesn't print anything extra), whereas if I run `npx prettier --loglevel debug .` it does print tons of logs.

What I've tried so far:

- Switched single and double quotes usage;
- Removed `--loglevel debug` parameter;
- Passed `-w` parameter;
- Simplified the glob match to something like `*.js` and other patterns, with no luck;
- Ran `npx git-format-staged --formatter 'echo "{}"' 'src/**/*.{js,jsx,ts}'` to see if it'd log anything, and it doesn't. It seems like git-format-staged swallows all logs 😅 
- Checked if `prettier` stdin linter is working, and it is:

```sh
$ echo ".selector {color:red}" | prettier --stdin-filepath "style.css"
.selector {
	color: red;
}
```

- Ran prettier formatter alone (without `git-format-staged`) on my test file specifically to see if it would format the fake lint changes I created, and it did format as expected.

Any help? It seems like `prettier` would be the most straight forward integration there is, yet I'm surprisingly unable to get it to work. FWIW I use `git-format-staged` with `SwiftFormat` and it works wonders 😄 

Thanks in advance!

**Comment by hallettj** [comment]
Hi; I'm sorry you're having trouble! I use git-format-staged with prettier, so yes it can work. I think the problem is the glob pattern. I tested with this command, and it worked in my repo:

```sh
npx git-format-staged --formatter 'npx prettier --loglevel debug --stdin-filepath "{}"' 'src/*.js' 'src/*.jsx' 'src/*.ts'
```

Those patterns will recursively match in subdirectories under `src/` even though they don't look like recursive patterns. I wanted to make git-format-staged dependency-free so I used Python's built-in [fnmatch](https://docs.python.org/3/library/fnmatch.html) globbing library. Unfortunately it doesn't work like normal shell globbing so you can't use `**` or `{}`.

Another important point is to make sure that you have staged changes to reformat. Git-format-staged will ignore changed files that are not staged, and it will ignore unchanged files. 

I think the reason you are not getting any debug output from prettier is because git-format-staged wasn't matching any files, and so prettier was not running at all. If prettier does run you will see debugging output. It might be a good idea for me to add an option to output a warning if no files were matched to help troubleshoot.

> Switched single and double quotes usage;

Good idea to try this, but it shouldn't make a difference.

> Removed `--loglevel debug` parameter;

Makes sense.

> Passed `-w` parameter;

I expect prettier to ignore the `-w` parameter when used with git-format-staged because it gets input via stdin. I think that option only works with file inputs. When it is working correctly it is not supposed to write to repo files directly anyway - it writes changes to new blobs in the git object database.

> Simplified the glob match to something like `*.js` and other patterns, with no luck;

This should have worked. So there might be more than one issue. Please let me know if the command I put in above still doesn't work.

> Ran `npx git-format-staged --formatter 'echo "{}"' 'src/**/*.{js,jsx,ts}'` to see if it'd log anything, and it doesn't. It seems like git-format-staged swallows all logs

This didn't work because git-format-staged runs the formatter command once for each matched file - that means for each file that matches the given globs, _and_ that has staged changes. The reason you didn't see any output is because this command did not match any files.

**Comment by rogerluan** [comment]
Thanks a lot for the thorough explanation @hallettj ! Changing the glob matching did the trick for me!
I guess when I tried other glob patterns there were other issues present in my command that made me think the changing the glob didn't fix it, but this actually did it.

I've opened a PR to improve the documentation on this topic 💪

**Comment by hallettj** [comment]
Nice, I'm glad to hear things are working. I'll look into that PR.
