### ISSUE TITLE
Feature Request: Enable File Modifications In-Place Instead of Depending on Stdin/Stdout

### ISSUE THREAD

**Issue by rogerluan** [hallettj/git-format-staged#64]
Hey 👋 

First of all I'd like to say I love `git-format-staged` and I've been a huge advocate of it out there 😄 

One challenge I've faced while using it is that it requires the formatters to support stdin/stdout formatting, and some formatters only have in-place file changes.

For this reason, I had to open issues in well known repositories like https://github.com/pinterest/ktlint/issues/1153 and https://github.com/realm/SwiftLint/issues/3636 for them to support stdin/stdout features.

However, I believe this would be a large feature to be implemented by the maintainers of those formatters, and it might not ever be done at all. And even if someone implements it for one of them, it would require all of the formatters out there to adhere to this feature, so it's not really 'scalable' 🤷 

My question (and request) is whether it's possible to implement this in `git-format-staged` instead, which would essentially add support to all formatters that make use of in-place file modifications instead of stdin/stdout. Would this be against the "nature" or "core mechanics" of `git-format-staged`?

Appreciate any input!

**Comment by hallettj** [comment]
Thanks for the advocacy, and thanks for your continuing feedback!

There are some ways that git-format-staged could be adapted for formatters
that modify files in place. But there are enough potential issues that I
think that building that functionality into git-format-staged itself is
probably not the best way to go. Modifying working tree files in place is
contrary to the philosophy I'm going for because I specifically want to
avoid dealing with automatically staging results of running a formatter.
The staged file is a file in the git object database, but we can't run a
formatter on that file because modifying it in place would break the
contract that object files never change. I think the best option that would
be compatible with the git-format-staged philosophy would be to use an
external command to write staged file content to a temporary file, run the
formatter on the temporary file, and output the new content. There might be
an existing command out there that does that, but here is a quick version
that I came up with:

```bash
#!/bin/bash
# with-temp-file.sh

set -e

# The name of the original file in the repository working tree, passed to
this
# script as an argument via the `{}` placeholder in the git-format-staged
# command.
filename="$1"

# Everything after the first argument to with-temp-file.sh is executed as
the
# formatter command. The path to the file to format will be appended
# automatically.
formatter_command="${@:2}"

# Create a temporary file - for example if the original file is called
# `index.ts` this will create a file in your system's temporary file
directory
# called something like `70bF7_index.ts`
tmpfile=$(mktemp "XXXXX_$filename")

# Get content of the staged file from stdin and write it to the temporary
file.
cat - > $tmpfile

# Run your formatter command.
eval $formatter_command $tmpfile

# Output the updated file content to stdout.
cat $tmpfile

# Clean up the temporary file.
rm $tmpfile
```

And that could be called like this:

    $ git-format-staged --formatter 'with-temp-file.sh "{}" ktlint -F'
'src/*.kt'

I don't think that will work in every case because the temporary file
created by that script will not be in the project directory. Some
formatters look for configuration files in the parent directories of a
source file, and if the source file is in `/tmp/` the formatter won't find
them. The script could be modified to create the temporary file somewhere
in the project directory. But I think there is enough nuance that a
one-size-fits-all solution might not be the best way to go. Still it might
be worthwhile to include something like that script in the documentation.

**Comment by rogerluan** [comment]
Thanks for your prompt reply @hallettj ! 🙌 

I totally understand (and appreciate) the fact that the philosophy of this tool does not aim to modify the actual files. But I was hoping we could modify **_staged_** files in place 😞

>we can't run a formatter on that file because modifying it in place would break the contract that object files never change

What is this "contract that object files never change" that you're referring to? Is this a contract specified by git itself?

>I don't think that will work in every case because the temporary file created by that script will not be in the project directory.

Given your knowledge, is this the only issue you foresee with this approach? If we assume that the majority of the projects have a single linter config file (instead of multiple, on a per-directory basis), then the user can pass the path of the config file in the lint command and everything would work as expected, right? That should cover the case for all that user base, which would be amazing.

Moreover, if this solution (which I find quite creative tbh 👏 ) could perhaps be incorporated into the main script itself? Or would we have to "download" two scripts? Perhaps there's a minor usability improvement we could think of here 😊 although I see no strong problems with the current proposal, from a usability standpoint.

Again, I appreciate your work towards this goal! It will be super beneficial for the mobile development community (SwiftLint, ktlint, detekt), as well as any other languages that don't support stdin/stdout linters 🤗

**Comment by hallettj** [comment]
I'm very sorry for taking so long to reply. I don't have a lot of time for spare-time projects. It would be great to have a wrapper to make and formatter pipeable - but I don't think it's a trivial problem, and it would take time. There are other things I want to spend that time on that are more important to me.

**Comment by rogerluan** [comment]
All good @hallettj ! Thanks for taking the time to respond and consider 🤗 take care!

**Comment by rogerluan** [comment]
@hallettj perhaps leave the issue open instead, so other contributors could see it and decide to pick it up? 😃
